'use strict';
function fetchLocal(url) {
    return new Promise(function (resolve, reject) {
        var xhr = new XMLHttpRequest
        xhr.onload = function () {
            resolve(new Response(xhr.response, { status: xhr.status }))
        }
        xhr.onerror = function () {
            reject(new TypeError('Local request failed'))
        }
        xhr.open('GET', url)
        xhr.responseType = "arraybuffer";
        xhr.send(null)
    })
};
function u(f,a,b,c){f.v.sc(f.bb,a,b,c,void 0)}function D(f,a,b,c){f.v.ca?u(f,a,b,c):f.v.nf()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function H(f,a,b){f.v.C(f.bb,a,b)}function I(f,a){for(const [b,c]of a)H(f,b,c)}function K(f){f.Tb||(f.v.Ye(f.he),f.Tb=!0)}window.Ca=class{constructor(f,a){this.v=f;this.bb=a;this.Tb=!1;this.he=()=>this.Fa()}ld(){}Fa(){}};function L(f){-1!==f.Sa&&(self.clearTimeout(f.Sa),f.Sa=-1)}
window.Pe=class{constructor(f,a){this.Sc=f;this.Ag=a;this.Sa=-1;this.Ub=-Infinity;this.ie=()=>{this.Sa=-1;this.Ub=Date.now();this.hb=!0;this.Sc();this.hb=!1};this.Rd=this.hb=!1}c(){L(this);this.ie=this.Sc=null}};"use strict";
function N(f,a){const b=a.elementId,c=f.pd(b,a);f.Y.set(b,c);c.style.boxSizing="border-box";a.isVisible||(c.style.display="none");a=f.Cc(c);a.addEventListener("focus",()=>{O(f,"elem-focused",b)});a.addEventListener("blur",()=>{O(f,"elem-blurred",b)});f.Ob&&document.body.appendChild(c)}function P(f,a){H(f,"get-element",b=>{const c=f.Y.get(b.elementId);return a(c,b)})}function O(f,a,b){var c;c||(c={});c.elementId=b;u(f,a,c)}
window.Be=class extends self.Ca{constructor(f,a){super(f,a);this.Y=new Map;this.Ob=!0;I(this,[["create",b=>N(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Ob&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Ob&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ob){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.yc(c,b)}}],["focus",b=>this.Mc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);P(this,b=>b)}pd(){throw Error("required override");}yc(){throw Error("required override");}Cc(f){return f}Mc(f){const a=this.Cc(this.Y.get(f.elementId));
f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="";return h.Lg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.Pg+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}c=!0}return g}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const C=[],G=new Map,z=new Map;let J=0;const E=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");E.push(h)};const M=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.fa=class h{constructor(d){this.ca=d.Rg;this.pa=null;this.F="";this.fc=d.Og;this.wb={};this.La=this.vb=null;
this.Rb=[];this.kb=this.G=this.Qa=null;this.Pa=-1;this.Fg=()=>this.Lf();this.Oa=[];this.s=d.je;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.ia=null;"html5"!==
this.s&&"playable-ad"!==this.s||!this.ib;"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.vf(k));this.C("runtime",
"create-job-worker",()=>this.wf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Ed(d)):this.Ed(d)}c(){this.zc();this.pa&&(this.pa=this.pa.onmessage=null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.c(),this.La=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Ke(){return f&&"cordova"===this.s}rc(){const d=navigator.userAgent;return f&&M.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async Ed(d){"macos-wkwebview"===
this.s&&this.Qc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Wb={};await this.cf();for(let l=0,n=d.Ta.length;l<n;++l){var k=d.Ta[l].toLowerCase();this.Wb.hasOwnProperty(k)?d.Ta[l]={Lg:!0,Pg:this.Wb[k]}:this.ia.hasOwnProperty(k)&&(d.Ta[l]=URL.createObjectURL(this.ia[k]))}}d.Gg?this.F=d.Gg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.Tg&&(this.wb=d.Tg);k=new MessageChannel;this.pa=
k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Hf(l));this.kb=new self.Le(this);await Q(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.qf(d,k.port2):await this.pf(d,k.port2)}Dc(d){d=this.wb.hasOwnProperty(d)?this.wb[d]:d.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?
this.wb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(d.toLowerCase())?this.ia[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async lc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===this.s&&this.ib)return d=await this.xb(l.Kg?d:this.fc+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetchLocal(d);if(!d.ok)throw Error("failed to fetch worker script");
d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}Cd(d){var k=this.kb;return{baseUrl:this.F,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Wa(),projectData:d.Zg,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.Xg||"",exportType:d.je,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Yg,jobScheduler:{inputPort:k.Yc,outputPort:k.dd,maxNumWorkers:k.Cg},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Ke(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qf(d,k){var l=this.Dc(d.Sg);this.vb=
await this.lc(l,this.F,{type:"module",name:"Runtime",Kg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let n=d.kd||[],t=d.Ta;n=await Promise.all(n.map(q=>this.Ga(q)));t=await Promise.all(t.map(q=>this.Ga(q)));if("cordova"===this.s)for(let q=0,r=d.jc.length;q<r;++q){const y=d.jc[q],F=y[0];if(F===d.hd||"scriptsInEvents.js"===F||F.endsWith("/scriptsInEvents.js"))y[1]=await this.Ga(F)}this.vb.postMessage(Object.assign(this.Cd(d),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:d.jc,mainProjectScript:d.hd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...R(this.kb)]);this.Rb=C.map(q=>new q(this));this.Bd();self.c3_callFunction=(q,r)=>this.Qa.rf(q,r);"preview"===this.s&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async pf(d,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Rb=C.map(q=>new q(this));this.Bd();var l=d.Ta.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.kd)&&l.unshift(...d.kd);l=await Promise.all(l.map(q=>this.Ga(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=d.hd,t=d.jc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Ga(r),await b(r),"preview"!==this.s||l[q]||this.Md(q,"main script did not run to completion")}catch(y){this.Md(q,y)}else if("scriptsInEvents.js"===
q||q.endsWith("/scriptsInEvents.js"))r=await this.Ga(r),await b(r);"preview"===this.s&&"object"!==typeof self.Ug.Vg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.Cd(d),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:E}),this.Gd(),this.La=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.La,
d))}Md(d,k){this.Jb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Gd(){this.Jb()}Jb(){const d=window.Hg;d&&(d.parentElement.removeChild(d),window.Hg=null)}async wf(){const d=await S(this.kb);return{outputPort:d,transferables:[d]}}nf(){if(this.ca)throw Error("not available in worker mode");return this.La}sc(d,k,l,n,t){this.pa.postMessage({type:"event",
component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}ud(d,k,l,n,t){const q=J++,r=new Promise((y,F)=>{z.set(q,{resolve:y,reject:F})});this.pa.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.Bf(d);if("result"===k)this.Of(d);else if("runtime-ready"===k)this.Pf();else if("alert-error"===k)this.Jb(),alert(d.message);else if("creating-runtime"===k)this.Gd();else throw Error(`unknown message '${k}'`);
}Bf(d){const k=d.component,l=d.handler,n=d.data,t=d.responseId;if(d=G.get(k))if(d=d.get(l)){var q=null;try{q=d(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Ib(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Ib(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Ib(t,!1,""+r)}):this.Ib(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(d,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}Of(d){const k=d.responseId,l=d.isOk;d=d.result;const n=z.get(k);l?n.resolve(d):n.reject(d);z.delete(k)}C(d,k,l){let n=G.get(d);n||(n=new Map,G.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);n.set(k,l)}static Ba(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}Bd(){for(const d of this.Rb)if("runtime"===d.bb){this.Qa=d;return}throw Error("cannot find runtime DOM handler");
}Hf(d){this.sc("debugger","message",d)}Pf(){for(const d of this.Rb)d.ld()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Kb(d){e=!!d}Ye(d){this.Oa.push(d);this.Pc()}ag(d){d=this.Oa.indexOf(d);if(-1===d)throw Error("invalid callback");this.Oa.splice(d,1);this.Oa.length||this.zc()}Pc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Fg))}zc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Lf(){this.Pa=
-1;for(const d of this.Oa)d();this.Pc()}ua(d){this.Qa.ua(d)}Ea(d){this.Qa.Ea(d)}Oc(){this.Qa.Oc()}Db(d){this.Qa.Db(d)}Je(){return!!x["audio/webm; codecs=opus"]}async yg(d){d=await this.ud("runtime","opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Ie(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}td(d){return!this.Ie(d)}async Ga(d){return"cordova"===this.s&&(d.startsWith("file:")||this.ib&&this.td(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),
d=await this.xb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async vf(d){const k=d.filename;switch(d.as){case "text":return await this.Ae(k);case "buffer":return await this.xb(k);default:throw Error("unsupported type");}}od(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async Ae(d){d=await this.od(d);return await A(d)}Ac(){if(v.length&&!(8<=w)){w++;var d=v.shift();
this.df(d.filename,d.Qg,d.Jg)}}xb(d){return new Promise((k,l)=>{v.push({filename:d,Qg:n=>{w--;this.Ac();k(n)},Jg:n=>{w--;this.Ac();l(n)}});this.Ac()})}async df(d,k,l){try{const n=await this.od(d),t=await B(n);k(t)}catch(n){l(n)}}Qc(d){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async cf(){const d=[];for(const [k,
l]of Object.entries(this.ia))d.push(this.bf(k,l));await Promise.all(d)}async bf(d,k){if("object"===typeof k)this.ia[d]=new Blob([k.str],{type:k.type}),this.Wb[d]=k.str;else{let l=await this.lf(k);l||(l=this.ff(k));this.ia[d]=l}}async lf(d){try{return await (await fetchLocal(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}ff(d){d=this.Vf(d);return this.af(d.data,d.Mg)}Vf(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Mg:d,data:l}}af(d,k){var l=d.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,y;for(y=r=0;r<n;++r)q[r]=d.charCodeAt(y++)|d.charCodeAt(y++)<<8|d.charCodeAt(y++)<<16|d.charCodeAt(y++)<<24;for(l&=
3;l--;)t[y]=d.charCodeAt(y),++y;return new Blob([t],{type:k})}}}"use strict";
{const f=self.fa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function x(e){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await x(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(e)})}async function v(e,h,d){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function z(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function J(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,d,k,l){e=await v(e,h,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,h,d);return n};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ba(class extends self.Ca{constructor(e){super(e,"runtime");this.Wd=!0;this.Ra=-1;this.fd="any";this.Nd=this.Od=!1;this.Ka=
this.sb=this.ya=null;this.bc=this.ac=0;e.C("canvas","update-size",k=>this.Sf(k));e.C("runtime","invoke-download",k=>this.Ff(k));e.C("runtime","raster-svg-image",k=>this.Mf(k));e.C("runtime","get-svg-image-size",k=>this.Df(k));e.C("runtime","set-target-orientation",k=>this.Qf(k));e.C("runtime","register-sw",()=>this.Nf());e.C("runtime","post-to-debugger",k=>this.Id(k));e.C("runtime","go-to-script",k=>this.Id(k));e.C("runtime","before-start-ticking",()=>this.uf());e.C("runtime","debug-highlight",k=>
this.xf(k));e.C("runtime","enable-device-orientation",()=>this.$e());e.C("runtime","enable-device-motion",()=>this.Ze());e.C("runtime","add-stylesheet",k=>this.tf(k));e.C("runtime","alert",k=>this.Hc(k));e.C("runtime","hide-cordova-splash",()=>this.Ef());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const d=e.G;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",
z);d.addEventListener("selectstart",z);d.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),d.addEventListener("pointerdown",z)):d.addEventListener("touchstart",z);this.pb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",J,{passive:!1});window.addEventListener("wheel",J,{passive:!1});window.addEventListener("resize",
()=>this.Tf());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",k=>this.Jc(k));window.addEventListener("webkitfullscreenerror",k=>this.Jc(k));window.addEventListener("mozfullscreenerror",k=>this.Jc(k));e.rc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Uf(k);this.Ma=new Set;this.Xb=new WeakSet;this.oa=!1}uf(){"cordova"===this.v.s?(document.addEventListener("pause",()=>this.Nc(!0)),document.addEventListener("resume",()=>this.Nc(!1))):document.addEventListener("visibilitychange",()=>this.Nc(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}ld(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:M()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||w(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Hd("keydown",h));window.addEventListener("keyup",h=>this.Hd("keyup",h));window.addEventListener("dblclick",h=>this.Kc("dblclick",h,c));window.addEventListener("wheel",h=>this.Jf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Ec(h);this.Za("pointerdown",h)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Pe(()=>this.jf(),5),this.sb.Rd=!0,window.addEventListener("pointerrawupdate",h=>this.Kf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Ec(h);this.Lc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Lc("pointermove",h)),window.addEventListener("mouseup",h=>this.Lc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Ec(h);this.Hb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Hb("pointermove",h)),window.addEventListener("touchend",h=>this.Hb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Hb("pointercancel",h)));const e=()=>this.Oc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}$a(e,h){u(this,e,h||null,m)}wa(){return this.v.wa()}va(){return this.v.va()}Tf(){const e=this.wa(),h=this.va();this.$a("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()});this.v.rc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Jd(e,h,0))}bg(e,h,d){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Jd(e,
h,d),48)}Jd(e,h,d){const k=this.wa(),l=this.va();this.Ra=-1;k!=e||l!=h?this.$a("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>d&&this.bg(k,l,d+1)}Qf(e){this.fd=e.targetOrientation}ug(){const e=this.fd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const e=f.Wa();e&&"any"!==this.fd&&this.ug();u(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Jc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",
{isFullscreen:f.Wa(),innerWidth:this.wa(),innerHeight:this.va()})}Nc(e){e?this.v.zc():this.v.Pc();u(this,"visibilitychange",{hidden:e})}Hd(e,h){"Backspace"===h.key&&z(h);const d=b.get(h.code)||h.code;D(this,e,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Jf(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},c)}Kc(e,h,d){a(h)||D(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},d)}Lc(e,h){if(!a(h)){var d=this.pb;"pointerdown"===e&&0!==d?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,
movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.pb=h.buttons;this.Kc(h.type,h,g)}}Za(e,h){if(this.sb&&"pointermove"!==e){var d=this.sb;d.hb||(L(d),d.Ub=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.pb);D(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||
0)+this.ac,movementY:(h.movementY||0)+this.bc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);this.bc=this.ac=0;"mouse"===h.pointerType&&(d="mousemove","pointerdown"===e?d="mousedown":"pointerup"===e&&(d="mouseup"),this.Kc(d,h,g),this.pb=h.buttons)}Kf(e){this.Ka&&(this.ac+=this.Ka.movementX||0,this.bc+=this.Ka.movementY||0);this.Ka=e;e=this.sb;if(-1===e.Sa){var h=Date.now(),
d=h-e.Ub,k=e.Ag;d>=k&&e.Rd?(e.Ub=h,e.hb=!0,e.Sc(),e.hb=!1):e.Sa=self.setTimeout(e.ie,Math.max(k-d,4))}}jf(){this.Za("pointermove",this.Ka);this.Ka=null}Hb(e,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];D(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}Ec(e){window!==window.top&&window.focus();this.Fd(e.target)&&document.activeElement&&!this.Fd(document.activeElement)&&document.activeElement.blur()}Fd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}$e(){this.Od||(this.Od=!0,window.addEventListener("deviceorientation",e=>this.zf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.Af(e)))}Ze(){this.Nd||(this.Nd=!0,window.addEventListener("devicemotion",e=>this.yf(e)))}zf(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},c)}Af(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},c)}yf(e){let h=null;var d=e.acceleration;d&&(h=
{x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=e.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},c)}Sf(e){const h=this.v.G;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Wd&&(h.style.display=
"",this.Wd=!1)}Ff(e){const h=e.url;e=e.filename;const d=document.createElement("a"),k=document.body;d.textContent=e;d.href=h;d.download=e;k.appendChild(d);d.click();k.removeChild(d)}async Mf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Df(e){return await self.C3_GetSvgImageSize(e.blob)}async tf(e){await p(e.url)}Oc(){var e=
[...this.Ma];this.Ma.clear();if(!this.oa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Xb.has(h)||this.Ma.add(h)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Xb.delete(e);let h;try{h=e.play()}catch(d){this.Ma.add(e);return}h&&h.catch(()=>{this.Xb.has(e)||this.Ma.add(e)})}Ea(e){this.Ma.delete(e);this.Xb.add(e)}Db(e){this.oa=!!e}Ef(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}xf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),
this.ya.id="inspectOutline",document.body.appendChild(this.ya));var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Nf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Id(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}rf(e,h){return this.v.ud(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Hc(e){alert(e.message)}Uf(e){"entered-fullscreen"===
e?(f.Kb(!0),this.Ya()):"exited-fullscreen"===e?(f.Kb(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function Q(f){if(f.zg)throw Error("already initialised");f.zg=!0;var a=f.ec.Dc("dispatchworker.js");f.Uc=await f.ec.lc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Yc=a.port1;f.Uc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.dd=await S(f)}function R(f){return[f.Yc,f.dd]}
async function S(f){const a=f.Xd.length;var b=f.ec.Dc("jobworker.js");b=await f.ec.lc(b,f.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;f.Uc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);f.Xd.push(b);return g.port1}
self.Le=class{constructor(f){this.ec=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.fc;this.Cg=Math.min(navigator.hardwareConcurrency||2,16);this.Uc=null;this.Xd=[];this.dd=this.Yc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fa({Rg:!1,Sg:"workermain.js",Ta:["scripts/c3runtime.js"],jc:[],hd:"",Og:"scripts/",kd:[],je:"html5"}));"use strict";
async function T(f,a){a=a.type;let b=!0;0===a?b=await U():1===a&&(b=await V());u(f,"permission-result",{type:a,result:b})}async function U(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function V(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.fa.Ba(class extends self.Ca{constructor(f){super(f,"touch");H(this,"request-permission",a=>T(this,a))}});"use strict";
self.fa.Ba(class extends self.Ca{constructor(f){super(f,"mouse");I(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{u(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{u(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";
{const f=180/Math.PI;self.da=class extends self.Ca{constructor(a){super(a,"audio");this.Qb=this.f=null;this.Sb=this.Xc=!1;this.ra=()=>this.vg();this.aa=[];this.D=[];this.ha=null;this.Yd="";this.Zd=-1;this.rb=new Map;this.ad=1;this.oa=!1;this.gd=0;this.hc=1;this.Vc=0;this.ae="HRTF";this.Sd="inverse";this.be=600;this.$d=1E4;this.de=1;this.Ud=this.ed=!1;this.ge=this.v.Je();this.ba=new Map;this.Ia=new Set;this.Zc=!1;this.bd="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.If(b,c);this.Pb=null;
self.C3Audio_GetOutputStream=()=>this.Cf();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.ef(b)],["play",b=>this.Wf(b)],["stop",b=>this.sg(b)],["stop-all",()=>this.tg()],["set-paused",b=>this.lg(b)],["set-volume",b=>this.qg(b)],["fade-volume",b=>this.kf(b)],["set-master-volume",b=>this.jg(b)],["set-muted",b=>this.kg(b)],["set-silent",b=>this.ng(b)],["set-looping",b=>this.ig(b)],["set-playback-rate",b=>this.mg(b)],["seek",b=>this.cg(b)],["preload",b=>this.Xf(b)],["unload",b=>
this.wg(b)],["unload-all",()=>this.xg()],["set-suspended",b=>this.og(b)],["add-effect",b=>this.zd(b)],["set-effect-param",b=>this.fg(b)],["remove-effects",b=>this.Zf(b)],["tick",b=>this.Rf(b)],["load-state",b=>this.Gf(b)]])}async ef(a){a.isiOSCordova&&(this.ed=!0);this.gd=a.timeScaleMode;this.ae=["equalpower","HRTF","soundfield"][a.panningModel];this.Sd=["linear","inverse","exponential"][a.distanceModel];this.be=a.refDistance;this.$d=a.maxDistance;this.de=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ge||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Ad();this.f.onstatechange=()=>{"running"!==this.f.state&&this.Ad()};this.Qb=this.f.createGain();this.Qb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.mc();try{await Promise.all(a.preloadList.map(c=>this.Fb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}Ad(){this.Sb||(this.Xc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Sb=!0)}gf(){this.Sb&&(this.Xc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Sb=!1)}vg(){if(!this.Xc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.gf()}}W(){return this.f}mc(){return this.f.currentTime}sa(){return this.Qb}rd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.sa()}ke(a,b){a=a.toLowerCase();let c=this.ba.get(a);
c||(c=[],this.ba.set(a,c));b.hg(c.length);b.pg(a);c.push(b);this.Ld(a)}Ld(a){let b=this.sa();const c=this.ba.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.sa()):p.S(c[g+1].P())}}for(const g of this.ma(a))g.Qe(b);this.za&&this.bd===a&&(this.za.disconnect(),this.za.connect(b))}zb(){return this.ad}Ab(){return this.oa}gg(){this.Ud=!0}De(a,b){return b?this.v.yg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}ua(a){this.v.ua(a)}Ea(a){this.v.Ea(a)}vd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Re(){let a=0;for(let b=0,c=this.aa.length;b<c;++b){const g=this.aa[b];this.aa[a]=g;g.ta()?g.c():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.D)self.da.Ee(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Fb(a,b,c,g,m){for(const p of this.aa)if(p.Va()===b)return await W(p),
p;if(m)return null;g&&(this.ed||this.Ud)&&this.Re();m="audio/webm; codecs=opus"===c&&!this.ge;g&&m&&this.gg();a=!g||this.ed||m?new self.ye(this,a,b,c,g,m):new self.we(this,a,b,c,g);this.aa.push(a);await W(a);return a}async Bc(a,b,c,g,m){for(const p of this.D)if(p.Va()===b&&(p.kc()||m))return p.Te(g),p;a=await this.Fb(a,b,c,m);g="html5"===a.Rc?new self.xe(a.i,a,g):new self.ze(a.i,a,g);this.D.push(g);return g}Xe(a){let b=this.rb.get(a);if(!b){let c=null;b={jd:0,Ng:new Promise(g=>c=g),resolve:c};this.rb.set(a,
b)}b.jd++}$f(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.jd--;0===b.jd&&(b.resolve(),this.rb.delete(a))}xc(a){a||(a=this.Yd);return(a=this.rb.get(a))?a.Ng:Promise.resolve()}Gb(){if(0<this.Ia.size)K(this);else for(const a of this.D)if(a.sd()){K(this);break}}Fa(){for(var a of this.Ia)a.Fa();a=this.mc();for(var b of this.D)b.Fa(a);b=this.D.filter(c=>c.sd()).map(c=>c.Ua());u(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Ia].map(c=>c.Ge())});0===b.length&&
0===this.Ia.size&&this.Tb&&(this.v.ag(this.he),this.Tb=!1)}tc(a,b,c){u(this,"trigger",{type:a,tag:b,aiid:c})}async Wf(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,x=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Yd=p;this.Xe(p);try{this.ha=await this.Bc(b,c,g,p,m),v?(this.ha.Cb(!0),this.ha.Se(v.x,v.y,v.angle,
v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Ue(v.uid)):this.ha.Cb(!1),this.ha.Play(x,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.$f(p)}K(this)}sg(a){a=a.tag;for(const b of this.ma(a))b.na()}tg(){for(const a of this.D)a.na()}lg(a){const b=a.tag;a=a.paused;for(const c of this.ma(b))a?c.Xa():c.Bb();this.Gb()}qg(a){const b=a.tag;a=a.vol;for(const c of this.ma(b))c.Eb(a)}async kf(a){const b=a.tag,c=a.vol,g=a.duration;
a=a.stopOnEnd;await this.xc(b);for(const m of this.ma(b))m.Fe(c,g,a);this.Gb()}jg(a){this.ad=a.vol;for(const b of this.D)b.Mb()}kg(a){const b=a.tag;a=a.isMuted;for(const c of this.ma(b))c.wd(a)}ng(a){this.oa=a.isSilent;this.v.Db(this.oa);for(const b of this.D)b.Lb()}ig(a){const b=a.tag;a=a.isLooping;for(const c of this.ma(b))c.vc(a)}async mg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const c of this.ma(b))c.yd(a)}async cg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const c of this.ma(b))c.uc(a)}async Xf(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.Bc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async wg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}xg(){for(const a of this.aa)a.c();this.aa.length=0}og(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.wc(a);a&&this.f.suspend&&this.f.suspend()}Rf(a){this.hc=a.timeScale;this.Vc=a.gameTime;this.Zd=a.tickCount;if(0!==
this.gd)for(var b of this.D)b.Ha();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ga===a&&g.xd(c.x,c.y,c.angle)}}async zd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.qe(this,...g);else if("delay"===b)g=new self.oe(this,...g);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.ne(this,b.$,...g);g.dg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.re(this,...g);else if("phaser"===b)g=new self.te(this,...g);else if("gain"===b)g=new self.se(this,...g);else if("tremolo"===b)g=new self.ve(this,...g);else if("ringmod"===b)g=new self.ue(this,...g);else if("distortion"===b)g=new self.pe(this,...g);else if("compressor"===b)g=new self.me(this,...g);else if("analyser"===b)g=new self.le(this,...g);else throw Error("invalid effect type");this.ke(c,
g);this.Kd()}fg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Kd())}Zf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const c of b)c.c();this.ba.delete(a);this.Ld(a)}}We(a){this.Ia.add(a);this.Gb()}Yf(a){this.Ia.delete(a)}Kd(){this.Zc||(this.Zc=!0,Promise.resolve().then(()=>this.hf()))}hf(){const a={};for(const [b,c]of this.ba)a[b]=c.map(g=>g.Ua());u(this,"fxstate",{fxstate:a});this.Zc=!1}async Gf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.ta()&&1===b||(c.ta()||2!==b)&&c.na();for(const g of this.ba.values())for(const m of g)m.c();this.ba.clear();this.hc=a.timeScale;this.Vc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.oa=a.isSilent;this.v.Db(this.oa);this.ad=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.zd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.sf(g,b)));this.Gb()}async sf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,x=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Bc(c,g,m,x,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Oe(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Xa();b.Gc(a)}}}If(a,b){this.za&&this.za.disconnect();this.bd=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.rd(this.bd))}Cf(){this.Pb||(this.Pb=this.f.createMediaStreamDestination(),
this.Qb.connect(this.Pb));return this.Pb.stream}static Ee(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ve(a){return a*f}static Ce(a){return Math.pow(10,a/20)}static qd(a){return Math.max(Math.min(self.da.Ce(a),1),0)}static Ne(a){return Math.log(a)/Math.log(10)*20}static Me(a){return self.da.Ne(Math.max(Math.min(a,1),0))}static Ig(a,b){return 1-Math.exp(-b*a)}};self.fa.Ba(self.da)}"use strict";function W(f){f.Vb||(f.Vb=f.Fc());return f.Vb}
self.md=class{constructor(f,a,b,c,g){this.i=f;this.Eg=a;this.Aa=b;this.R=c;this.Bg=g;this.Rc="";this.Vb=null}c(){this.Vb=this.i=null}Fc(){}W(){return this.i.W()}oc(){return this.Eg}Va(){return this.Aa}nc(){return this.R}ta(){return this.Bg}ea(){}};"use strict";
self.we=class extends self.md{constructor(f,a,b,c,g){super(f,a,b,c,g);this.Rc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.W().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,m);this.lb&&(this.lb(m),this.lb=this.mb=null)})}c(){this.i.vd(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.c()}Fc(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.K.src=this.Aa})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function X(f){if(f.xa)return f.xa;var a=f.i.v;if("cordova"===a.s&&a.td(f.Aa)&&a.ib)f.xa=await a.xb(f.Aa);else{a=await fetchLocal(f.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.xa=await a.arrayBuffer()}}async function Y(f){if(f.$)return f.$;f.$=await f.i.De(f.xa,f.Dg);f.xa=null}
self.ye=class extends self.md{constructor(f,a,b,c,g,m){super(f,a,b,c,g);this.Rc="webaudio";this.$=this.xa=null;this.Dg=!!m}c(){this.i.vd(this);this.$=this.xa=null;super.c()}async Fc(){try{await X(this),await Y(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.nd=class{constructor(a,b,c){this.i=a;this.L=b;this.Z=c;this.Nb=f++;this.M=this.W().createGain();this.M.connect(this.sa());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.ub=1;this.Ja=!1;this.qa=1;a=this.i.gd;this.$c=1===a&&!this.ta()||2===a;this.fb=this.ga=-1;this.fe=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.rd(this.Z)}zb(){return this.i.zb()}yb(){return this.$c?
this.i.Vc:performance.now()/1E3}oc(){return this.L.oc()}Va(){return this.L.Va()}nc(){return this.L.nc()}ta(){return this.L.ta()}Te(a){this.Z=a}T(){}kc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}sd(){return!this.I&&!this.T()}Da(){}ea(){return this.L.ea()}Play(){}na(){}Xa(){}Bb(){}Eb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.pc()}Fe(a,b,c){if(!this.Ja){a*=this.zb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.mc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.ub=a;this.fb=b;this.fe=c}}Mb(){this.Eb(this.ub)}Fa(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.fe&&this.na(),this.i.tc("fade-ended",this.Z,this.Nb))}pc(){const a=this.ub*this.zb();return isFinite(a)?a:0}wd(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Lb())}Ab(){return this.i.Ab()}Lb(){}vc(){}yd(a){this.qa!==a&&(this.qa=a,this.Ha())}Ha(){}uc(){}wc(){}Cb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.ae,this.B.distanceModel=
this.i.Sd,this.B.refDistance=this.i.be,this.B.maxDistance=this.i.$d,this.B.rolloffFactor=this.i.de),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.sa())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Se(a,b,c,g,m,p){this.jb&&(this.xd(a,b,c),a=self.da.Ve,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}xd(a,b,c){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(c),this.ja[1]=Math.sin(c),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Ue(a){this.ga=a}qc(){}Qe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Nb,tag:this.Z,duration:this.ea(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Da(),playbackRate:this.qa,uid:this.ga,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.qc(),pan:this.He()}}Gc(a){this.yd(a.playbackRate);this.wd(a.isMuted)}He(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Oe(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.xe=class extends self.nd{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Ic()}c(){this.na();this.L.qb.disconnect();super.c()}O(){return this.L.O()}Ic(){this.I=!0;this.ga=-1;this.i.tc("ended",this.Z,this.Nb)}T(){return this.O().ended}kc(){return this.I?!0:this.T()}Da(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==f&&(c.loop=f);this.Eb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.ua(c);this.H=this.I=!1;this.V=f;this.qa=1}na(){const f=this.O();f.paused||f.pause();this.i.Ea(f);this.I=!0;this.H=!1;this.ga=-1}Xa(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Ea(f);this.H=!0}}Bb(){!this.H||this.I||this.T()||(this.i.ua(this.O()),this.H=!1)}Lb(){this.O().muted=this.Ja||this.Ab()}vc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Ha(){let f=this.qa;this.$c&&(f*=this.i.hc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}uc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}qc(){return this.Da()}wc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.ua(this.O()),this.la=!1)}};"use strict";
function Z(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.ze=class extends self.nd{constructor(f,a,b){super(f,a,b);this.j=null;this.Yb=c=>this.Ic(c);this.Wc=!0;this.ab=null;this.N=this.Zb=this.$b=0;this.cd=1}c(){this.na();Z(this);this.Yb=null;super.c()}Ic(f){this.H||this.la||f.target!==this.ab||(this.I=this.Wc=!0,this.ga=-1,Z(this),this.i.tc("ended",this.Z,this.Nb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Wc}kc(){return!this.j||this.I?!0:this.T()}Da(){let f;f=this.H?this.N:this.Zb+(this.yb()-this.$b)*this.qa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,c){this.cd=1;this.Eb(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Yb;this.j.loop=f;this.j.start(c,b);this.H=this.I=this.Wc=!1;this.V=f;this.qa=1;this.$b=this.yb();this.Zb=b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.ga=-1}Xa(){this.H||this.I||this.T()||(this.N=this.Da(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Bb(){!this.H||this.I||this.T()||(Z(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Mb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.H=!1)}pc(){return super.pc()*this.cd}Lb(){this.cd=this.Ja||this.Ab()?0:1;this.Mb()}vc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ha(){let f=this.qa;this.$c&&(f*=this.i.hc);this.j&&(this.j.playbackRate.value=f)}uc(f){this.I||this.T()||(this.H?this.N=f:(this.Xa(),this.N=f,this.Bb()))}qc(){return this.N}wc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Da(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Mb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.la=!1)}Gc(f){super.Gc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Vd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}hg(a){this.Vd=a}pg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Z,params:this.g}}}
self.qe=class extends f{constructor(a,b,c,g,m,p,x){super(a);this.R="filter";this.g=[b,c,g,m,p,x];this.l=this.o();this.b=this.o();this.b.gain.value=x;this.a=this.o();this.a.gain.value=1-x;this.A=this.f.createBiquadFilter();this.A.type=b;this.A.frequency.value=c;this.A.detune.value=g;this.A.Q.value=m;this.A.gain.vlaue=p;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}c(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.A.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.A.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.A.gain,b,c,g)}}};self.oe=class extends f{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=c;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.da.qd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.eb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.ne=class extends f{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Qd=this.Pd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.f.createConvolver();this.cb.normalize=c;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}c(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}dg(a,b){this.Pd=a;this.Qd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Pd;a.bufferUrl="";a.bufferType=this.Qd;return a}};self.re=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.gb=this.o();this.gb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=g;this.J=this.o();this.J.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.u.connect(this.J);this.J.connect(this.U.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,c,g)}}};self.te=class extends f{constructor(a,b,c,g,m,p,x){super(a);this.R="phaser";this.g=[b,c,g,m,p,x];this.l=this.o();this.a=this.o();this.a.gain.value=1-x/2;this.b=this.o();this.b.gain.value=x/2;this.A=this.f.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
c;this.A.Q.value=g;this.u=this.f.createOscillator();this.u.frequency.value=p;this.J=this.o();this.J.gain.value=m;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.u.connect(this.J);this.J.connect(this.A.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.A.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.A.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,c,g)}}};self.se=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.da.qd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.ve=class extends f{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.J=this.o();this.J.gain.value=c/2;this.u.connect(this.J);this.J.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.J.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.J.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,c,g)}}};self.ue=class extends f{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.tb=this.o();this.tb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.tb.gain);this.u.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,c,g)}}};self.pe=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.dc=this.o();this.cc=this.o();this.eg(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ic=this.f.createWaveShaper();this.Tc=new Float32Array(65536);this.mf(b,c);this.ic.curve=this.Tc;this.l.connect(this.dc);this.l.connect(this.a);this.dc.connect(this.ic);this.ic.connect(this.cc);
this.cc.connect(this.b)}c(){this.l.disconnect();this.dc.disconnect();this.ic.disconnect();this.cc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}eg(a,b){.01>a&&(a=.01);this.dc.gain.value=a;this.cc.gain.value=Math.pow(1/a,.6)*b}mf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.rg(g,a,b);this.Tc[32768+c]=g;this.Tc[32768-c-1]=-g}}rg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.da.Ig(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.me=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.le=class extends f{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Td=new Float32Array(this.h.frequencyBinCount);this.ee=new Uint8Array(b);this.ce=this.Na=0;this.i.We(this)}c(){this.i.Yf(this);this.h.disconnect();super.c()}Fa(){this.h.getFloatFrequencyData(this.Td);this.h.getByteTimeDomainData(this.ee);const a=this.h.fftSize;let b=this.Na=0;for(var c=0;c<a;++c){let g=(this.ee[c]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}c=self.da.Me;this.Na=c(this.Na);this.ce=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ge(){return{tag:this.Z,index:this.Vd,peak:this.Na,rms:this.ce,binCount:this.h.frequencyBinCount,freqBins:this.Td}}}}"use strict";function aa(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(f,"sw-message",a.data))}
function ba(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.fa.Ba(class extends self.Ca{constructor(f){super(f,"browser");this.s="";I(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>aa(this)],
["alert",a=>this.Hc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Mc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ba(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const c=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.Wg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.fa.Kb(!0),this.v.Qc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.fa.Kb(!1),this.v.Qc({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{u(this,"backbutton")})}Hc(f){alert(f.message)}Mc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{function f(a){a.stopPropagation()}self.fa.Ba(class extends self.Be{constructor(a){super(a,"button")}pd(a,b){const c=document.createElement("input");var g=c;b.isCheckbox?(c.type="checkbox",g=document.createElement("label"),g.appendChild(c),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):c.type="button";g.style.position="absolute";g.addEventListener("touchstart",
f);g.addEventListener("touchmove",f);g.addEventListener("touchend",f);g.addEventListener("mousedown",f);g.addEventListener("mouseup",f);g.addEventListener("keydown",f);g.addEventListener("keyup",f);c.addEventListener("click",()=>{var m={isChecked:c.checked};m.elementId=a;D(this,"click",m)});b.id&&(c.id=b.id);this.yc(g,b);return g}Dd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Cc(a){return this.Dd(a)}yc(a,b){const c=this.Dd(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;
a===c?c.value=b.text:a.lastChild.textContent=b.text}})};
