var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_GAMEOVER  = "YOU COMPLETED ";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_SUDOKU    = " SUDOKU";
var TEXT_IN        = " IN ";
var TEXT_HELP_USED = "YOU USED THE FOLLOWING HELP:";
var TEXT_HELPS_USED= "YOU USED THE FOLLOWING HELPS:";
var TEXT_HELP_NOTE = "NOTES AUTOFILL";
var TEXT_HELP_SOLVE= "SOLVER";
var TEXT_HELP_TIME = "SET NO TIME";
var TEXT_HELP_HINT = " HINT";
var TEXT_HELP_HINTS = " HINTS";
var TEXT_SCORE     = "SCORE:";
var TEXT_PLAY      = "PLAY";
var TEXT_RESTART   = "RESTART";
var TEXT_TIME      = "TIME";
var TEXT_GENERATE_SUDOKU = "GENERATING SUDOKU. PLEASE WAIT";
var TEXT_PAUSE     = "PAUSE";

var TEXT_NEW       = "NEW";
var TEXT_CONTINUE  = "CONTINUE";
var TEXT_WARNING_NEW_GAME   = "YOU HAVE A SAVED GAME IN PROGRESS, DO YOU WANT TO START A NEW SUDOKU ANYWAY?";
var TEXT_IOS_PRIVATE = 'Your web browser does not support storing settings locally. In Safari, the most common cause of this is using "Private Browsing Mode". Some info may not save or some features may not work properly';

var TEXT_DEVELOPED = "DEVELOPED BY";

var TEXT_INFO_SOLVE = "(all points lost)";
var TEXT_INFO_NOTE = "(half of all points lost)";
var TEXT_INFO_HINT = "points per hint)";

var TEXT_TOP_MODE  = "SELECT YOUR LEVEL";
var TEXT_EASY      = "BEGINNER";
var TEXT_MEDIUM    = "INTERMEDIATE";
var TEXT_HARD      = "ADVANCED";

var TEXT_HELP0     = "RULES";
var TEXT_HELP1     = "FILL IN THE BLANKS WITH NUMBERS FROM 1 TO 9. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN THE NUMBER 1 THROUGH 9 EXACTLY ONCE";

var TEXT_HELP0_PAGE2 = "HOW-TO";
var TEXT_HELP1_PAGE2 = "USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";
var TEXT_HELP1_MOB_PAGE2 = "USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";

var TEXT_HELP2_PAGE2 = '"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';
var TEXT_HELP3_PAGE2 = '"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';
var TEXT_HELP4_PAGE2 = 'MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK';

var TEXT_FILL_WITH_NOTE = "FILL THE BOARD WITH NOTES";
var TEXT_DELETE_ALL_NOTE = "DELETE ALL NOTES";
var TEXT_SOLVE = "SOLVE THE SUDOKU";
var TEXT_RESET = "RESET THE SUDOKU";
var TEXT_SETNOTIME = "PLAY WITHOUT TIME";
var TEXT_GETHINT = "GET A HINT";
var TEXT_FULLSCREEN = "FULL SCREEN";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";

